version: "2"
run:
  modules-download-mode: vendor
linters:
  default: none
  enable:
    - errcheck
    - exhaustive
    - forcetypeassert
    - govet
    - ineffassign
    - revive
    - staticcheck
    - unused
    - whitespace
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
        text: .*logger.Sync.*
    paths:
      - third_party$
      - builtin$
      - examples$
      - ".*/mocks"
      - "generated"
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
