name: build-commit

on:
  push:
    branches:
      - "**"
    tags:
      - "!"
  pull_request:
    branches:
      - master
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-test:
    uses: ./.github/workflows/build-and-test.yml
  build-docker:
    uses: ./.github/workflows/build-docker.yml